-
  branches:
    only:
      - master
  version: 1.0.0.{build}
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2015
  cache:
  - src\packages
  services:
    - mssql2014
  nuget:
    account_feed: true
    project_feed: true
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  before_build:
  - ps: >-
      nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json;

      nuget restore src;

      nuget install redis-64 -excludeversion;

      redis-64\tools\redis-server.exe --service-install;

      redis-64\tools\redis-server.exe --service-start;
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    server: https://www.nuget.org/
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    on:
      branch: master
  notifications:
  - provider: Slack
    auth_token:
      secure: ykFbdC7lkZWbEgA8/5cQo3c2+ISttLd1AvhAiXyJqd2eaCdR8p32kE2aHlTxmwFU
    channel: github
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

# Test config
-
  branches:
    only:
      - test
  version: 1.0.0.{build}-beta
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2015
  services:
    - mssql2014
  nuget:
    account_feed: true
    project_feed: true
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  before_build:
  - ps: >-
      nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json;

      nuget restore src;

      nuget install redis-64 -excludeversion;

      redis-64\tools\redis-server.exe --service-install;

      redis-64\tools\redis-server.exe --service-start;
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    server: https://www.nuget.org/
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    on:
      branch: master
  notifications:
  - provider: Slack
    auth_token:
      secure: ykFbdC7lkZWbEgA8/5cQo3c2+ISttLd1AvhAiXyJqd2eaCdR8p32kE2aHlTxmwFU
    channel: github
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true


# Dev config
-
  branches:
    only:
      - /[Dd]ev/
  version: 2.0.{build}-alpha
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2015
  services:
    - mssql2014
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  environment:
    # Don't report back to the mothership
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  init:
  - ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER + "alpha"
  before_build:
  - ps: >-
      $Env:LABEL

      nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json;

      nuget restore src;

      appveyor-retry dotnet restore -v Minimal;

      nuget install redis-64 -excludeversion;

      redis-64\tools\redis-server.exe --service-install;

      redis-64\tools\redis-server.exe --service-start;
  build_script:
  - dotnet build "src\Arragro.Common" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
  - dotnet build "tests\Arragro.TestBase" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
  - dotnet build "tests\Arragro.Common.Tests" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
  after_build:
    - dotnet pack "src\Arragro.Common" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
  test_script:
  - dotnet test "tests\Arragro.Common.Tests" -c %CONFIGURATION%
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  test: off
  artifacts:  
    - path: .\artifacts\**\*.nupkg
      name: NuGet
  deploy:
  - provider: NuGet
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    on:
      branch: dev
  notifications:
  - provider: Slack
    auth_token:
      secure: ykFbdC7lkZWbEgA8/5cQo3c2+ISttLd1AvhAiXyJqd2eaCdR8p32kE2aHlTxmwFU
    channel: github
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true