-
  branches:
    only:
      - master
  version: 1.0.0.{build}
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2017
  cache:
  - src\packages
  services:
    - mssql2016
  nuget:
    account_feed: false
    project_feed: false
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  before_build:
  - ps: >-
      nuget restore src;

      nuget install redis-64 -excludeversion;

      redis-64\tools\redis-server.exe --service-install;

      redis-64\tools\redis-server.exe --service-start;
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    server: https://www.nuget.org/
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    on:
      branch: master
  notifications:
  - provider: Slack
    auth_token:
      secure: ykFbdC7lkZWbEgA8/5cQo3c2+ISttLd1AvhAiXyJqd2eaCdR8p32kE2aHlTxmwFU
    channel: github
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

# Test config
-
  branches:
    only:
      - test
  version: 1.0.0.{build}-beta
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2017
  cache:
  - src\packages
  services:
    - mssql2016
  nuget:
    account_feed: false
    project_feed: false
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  before_build:
  - ps: >-
      nuget restore src;

      nuget install redis-64 -excludeversion;

      redis-64\redis-server.exe --service-install;

      redis-64\redis-server.exe --service-start;
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    server: https://www.nuget.org/
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    on:
      branch: master
  notifications:
  - provider: Slack
    auth_token:
      secure: ykFbdC7lkZWbEgA8/5cQo3c2+ISttLd1AvhAiXyJqd2eaCdR8p32kE2aHlTxmwFU
    channel: github
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true


# Dev config
-
  branches:
    only:
      - /[Dd]ev/
  version: 1.0.0.{build}-alpha
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2017
  cache:
  - src\packages
  services:
    - mssql2016
  nuget:
    account_feed: false
    project_feed: false
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  before_build:
  - ps: >-
      nuget restore src;

      nuget install redis-64 -excludeversion;

      redis-64\redis-server.exe --service-install;

      redis-64\redis-server.exe --service-start;
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    server: https://www.nuget.org/
    api_key:
      secure: F0ZPbEej7MlPRYAb43jRKMZdVDCWLEhfsgmx4o3YTSdcTKIGbOO92NL2LlHcjY1V
    on:
      branch: master
  notifications:
  - provider: Slack
    auth_token:
      secure: ykFbdC7lkZWbEgA8/5cQo3c2+ISttLd1AvhAiXyJqd2eaCdR8p32kE2aHlTxmwFU
    channel: github
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true